services:
  - type: redis
    name: rails-sales-import-redis
    plan: free
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []

  - type: web
    name: rails-sales-import-web
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build"
    startCommand: "./bin/thrust ./bin/rails server"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: rails-sales-import-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 1
      - key: RAILS_MAX_THREADS
        value: 5
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test
      - key: RAILS_SERVE_STATIC_FILES
        value: true
      - key: RAILS_LOG_TO_STDOUT
        value: true

  - type: worker
    name: rails-sales-import-worker
    runtime: ruby
    plan: free
    buildCommand: "./bin/render-build"
    startCommand: "bundle exec sidekiq -C config/sidekiq.yml"
    envVars:
      - key: REDIS_URL
        fromService:
          type: redis
          name: rails-sales-import-redis
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: RAILS_ENV
        value: production
      - key: BUNDLE_WITHOUT
        value: development:test
