---
:concurrency: 5
:timeout: 25
:verbose: false
:queues:
  - default

development:
  :concurrency: 2
  :verbose: true

test:
  :concurrency: 1

production:
  :concurrency: <%= ENV.fetch("WEB_CONCURRENCY", 2) %>
  :timeout: 30

:dead_timeout_in_seconds: 30
:dead_max_jobs: 10
